name: Rust

on:
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Install VisiData
      run: pip install visidata==$(cat .visidata-version)
    - name: Build
      run: cargo build --verbose
    - name: Install cargo-insta
      run: cargo install cargo-insta --locked
    - name: Run tests
      run: cargo insta test --unreferenced=reject
